### ISSUE TITLE
Text2SQL评估指标EX和TS

### ISSUE THREAD

**Issue by 123qwe1234512** [eosphoros-ai/DB-GPT-Hub#221]
想请问大佬们，评估指标EX和TS的区别。
有一篇论文《A comprehensive evaluation of ChatGPT’s zero-shot Text-to-SQL
capability》用到了VA EX TS三个指标，他使用的TS是来自《Semantic Evaluation for Text-to-SQL with Distilled Test Suites》这篇论文。
浅研究了那篇TS指标的论文，理解的是TS使用的评估数据库是经过蒸馏的精简测试套件，不知道是不是不对？
去找了第一篇论文EX的开源代码和第二篇TS的开源代码，evaluation.py中操作基本没有区别。

**Comment by wangzaistone** [comment]
you can  read the READMe  about " As the paper 《SQL-PALM: IMPROVED LARGE LANGUAGE MODEL ADAPTATION FOR TEXT-TO-SQL》 mentioned, "We consider two commonly-used evaluation metrics: execution accuracy (EX) and test-suite accuracy (TS). EX measures whether the SQL execution outcome matches ground truth (GT), whereas TS measures whether the SQL passes all EX evaluations for multiple tests, generated by database augmentation. Since EX contains false positives, we consider TS as a more reliable evaluation metric". "
